# action.yml
name: 'Current Branch'
description: 'Grab the current branch and/or tag of your repo 👍'
branding:
    icon: 'git-branch'
    color: 'black'
outputs:
  branch:
    description: 'Current branch name'
    value: ${{ steps.composite.outputs.branch }}
  tag:
    description: 'Corresponding branch tag'
    value: ${{ steps.composite.outputs.tag }}
runs:
  using: "composite"
  steps: 
    - run: |
        declare -A TAGS_MAP
        TAGS_MAP=( ["master"]="latest" ["development"]="development")

        BRANCH=$(echo ${GITHUB_REF} | sed -e "s/refs\/heads\///g")
        TAG=${TAGS_MAP[$BRANCH]}

        if [ $(echo ${GITHUB_REF} | sed -e "s/refs\/tags\///g") != ${GITHUB_REF} ]; then
          TAG="latest"
        fi

        echo "::set-output name=branch::${BRANCH}"
        echo "::set-output name=tag::${TAG}"
      shell: bash
      id: composite